# Copyright (c) 2016 Uber Technologies, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# DefaultServiceConfig stores the default service config for each service
DefaultServiceConfig:
  HyperbahnBootstrapFile: ""
  RingHosts: ""
  EnableLimits: true

# ServiceConfig overrides default config with service-specific config such as ports
ServiceConfig:
  cherami-inputhost:
    Port: 4240
    WebsocketPort: 6189
    tchannel:
      port: 4240
      disableHyperbahn: true
      logLevel: warn
      disableLogging: true
  cherami-storehost:
    Port: 4253
    WebsocketPort: 6191
    tchannel:
      port: 4253
      disableHyperbahn: true
      logLevel: warn
      disableLogging: true
  cherami-outputhost:
    Port: 4254
    WebsocketPort: 6190
    tchannel:
      port: 4254
      disableHyperbahn: true
      logLevel: warn
      disableLogging: true
  cherami-frontendhost:
    Port: 4922
    tchannel:
      port: 4922
      disableHyperbahn: true
      logLevel: warn
      disableLogging: true
  cherami-controllerhost:
    Port: 5425
    tchannel:
      port: 5425
      disableHyperbahn: true
      logLevel: warn
      disableLogging: true
  cherami-replicator:
    Port: 6280
    WebsocketPort: 6310
    tchannel:
      port: 6280
      disableHyperbahn: true
      logLevel: warn
      disableLogging: true

# MetadataConfig specifies location of the Cassandra and ketspace
MetadataConfig:
  CassandraHosts: ""
  Port: 9042
  Keyspace: "cherami"
  Consistency: "one"
  ClusterName: "base"
  NumConns: 1
  Authentication:
    Enabled: true
    Username: cassandra
    Password: cassandra

# ReplicatorConfig specifies 
ReplicatorConfig:
  DefaultAuthoritativeZone: "zone1"
  ReplicatorHosts:
    deployment1: 192.168.0.1
    deployment2: 192.168.0.2
  UseStandalone: "deployment1,deployment2"

# KafkaConfig specifies
KafkaConfig:
  kafkaClusterConfigFile: "../../config/local_kafka_clusters.yaml"

# Logging configuration
logging:
  level: error
  stdout: false

# DefaultDestinationConfig right now configures how many replicas you want
DefaultDestinationConfig:
  Replicas: 3

# StorageConfig specfies location of the message storage, and the UUID of the storage host. The UUID should be different in each host.
# StorageConfig:
#   BaseDir: ""
#   HostUUID: ""
